// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: zestchain/ad.proto

package types

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Ad struct {
	Index   string `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
	Title   string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Pot     uint64 `protobuf:"varint,3,opt,name=pot,proto3" json:"pot,omitempty"`
	Url     string `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	Msg     string `protobuf:"bytes,5,opt,name=msg,proto3" json:"msg,omitempty"`
	Tags    string `protobuf:"bytes,6,opt,name=tags,proto3" json:"tags,omitempty"`
	Prefs   string `protobuf:"bytes,7,opt,name=prefs,proto3" json:"prefs,omitempty"`
	Creator string `protobuf:"bytes,8,opt,name=creator,proto3" json:"creator,omitempty"`
}

func (m *Ad) Reset()         { *m = Ad{} }
func (m *Ad) String() string { return proto.CompactTextString(m) }
func (*Ad) ProtoMessage()    {}
func (*Ad) Descriptor() ([]byte, []int) {
	return fileDescriptor_74e00febbd518cae, []int{0}
}
func (m *Ad) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Ad) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Ad.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Ad) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ad.Merge(m, src)
}
func (m *Ad) XXX_Size() int {
	return m.Size()
}
func (m *Ad) XXX_DiscardUnknown() {
	xxx_messageInfo_Ad.DiscardUnknown(m)
}

var xxx_messageInfo_Ad proto.InternalMessageInfo

func (m *Ad) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

func (m *Ad) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Ad) GetPot() uint64 {
	if m != nil {
		return m.Pot
	}
	return 0
}

func (m *Ad) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Ad) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *Ad) GetTags() string {
	if m != nil {
		return m.Tags
	}
	return ""
}

func (m *Ad) GetPrefs() string {
	if m != nil {
		return m.Prefs
	}
	return ""
}

func (m *Ad) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func init() {
	proto.RegisterType((*Ad)(nil), "cytruslabs.zestchain.zestchain.Ad")
}

func init() { proto.RegisterFile("zestchain/ad.proto", fileDescriptor_74e00febbd518cae) }

var fileDescriptor_74e00febbd518cae = []byte{
	// 236 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x40, 0xe3, 0x36, 0x6d, 0xc1, 0x13, 0xb2, 0x18, 0x6e, 0xb2, 0x2a, 0xa6, 0x4e, 0x89, 0x10,
	0x5f, 0x00, 0x2b, 0x5b, 0x47, 0x36, 0x27, 0x31, 0xa9, 0xa5, 0xa4, 0xb6, 0x7c, 0x17, 0xa9, 0xe5,
	0x2b, 0xf8, 0x0e, 0xbe, 0x84, 0xb1, 0x23, 0x23, 0x4a, 0x7e, 0x04, 0xd9, 0x16, 0x84, 0xed, 0xbd,
	0x67, 0xeb, 0xa4, 0x3b, 0x2e, 0xde, 0x34, 0x52, 0x7d, 0x50, 0xe6, 0x58, 0xaa, 0xa6, 0x70, 0xde,
	0x92, 0x15, 0xb2, 0x3e, 0x93, 0x1f, 0xb0, 0x53, 0x15, 0x16, 0x7f, 0xcf, 0x33, 0xdd, 0x7d, 0x30,
	0xbe, 0x78, 0x6c, 0xc4, 0x2d, 0x5f, 0x99, 0x63, 0xa3, 0x4f, 0xc0, 0xb6, 0x6c, 0x77, 0xbd, 0x4f,
	0x12, 0x2a, 0x19, 0xea, 0x34, 0x2c, 0x52, 0x8d, 0x22, 0x6e, 0xf8, 0xd2, 0x59, 0x82, 0xe5, 0x96,
	0xed, 0xf2, 0x7d, 0xc0, 0x50, 0x06, 0xdf, 0x41, 0x1e, 0x7f, 0x05, 0x0c, 0xa5, 0xc7, 0x16, 0x56,
	0xa9, 0xf4, 0xd8, 0x0a, 0xc1, 0x73, 0x52, 0x2d, 0xc2, 0x3a, 0xa6, 0xc8, 0x61, 0xbe, 0xf3, 0xfa,
	0x15, 0x61, 0x93, 0xe6, 0x47, 0x11, 0xc0, 0x37, 0xb5, 0xd7, 0x8a, 0xac, 0x87, 0xab, 0xd8, 0x7f,
	0xf5, 0xe9, 0xf9, 0x73, 0x94, 0xec, 0x32, 0x4a, 0xf6, 0x3d, 0x4a, 0xf6, 0x3e, 0xc9, 0xec, 0x32,
	0xc9, 0xec, 0x6b, 0x92, 0xd9, 0xcb, 0x7d, 0x6b, 0xe8, 0x30, 0x54, 0x45, 0x6d, 0xfb, 0x72, 0xde,
	0xb8, 0x9c, 0x0f, 0x72, 0xfa, 0xc7, 0x74, 0x76, 0x1a, 0xab, 0x75, 0x3c, 0xd0, 0xc3, 0x4f, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xd9, 0x17, 0xda, 0x74, 0x36, 0x01, 0x00, 0x00,
}

func (m *Ad) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Ad) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Ad) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintAd(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.Prefs) > 0 {
		i -= len(m.Prefs)
		copy(dAtA[i:], m.Prefs)
		i = encodeVarintAd(dAtA, i, uint64(len(m.Prefs)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.Tags) > 0 {
		i -= len(m.Tags)
		copy(dAtA[i:], m.Tags)
		i = encodeVarintAd(dAtA, i, uint64(len(m.Tags)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.Msg) > 0 {
		i -= len(m.Msg)
		copy(dAtA[i:], m.Msg)
		i = encodeVarintAd(dAtA, i, uint64(len(m.Msg)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Url) > 0 {
		i -= len(m.Url)
		copy(dAtA[i:], m.Url)
		i = encodeVarintAd(dAtA, i, uint64(len(m.Url)))
		i--
		dAtA[i] = 0x22
	}
	if m.Pot != 0 {
		i = encodeVarintAd(dAtA, i, uint64(m.Pot))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Title) > 0 {
		i -= len(m.Title)
		copy(dAtA[i:], m.Title)
		i = encodeVarintAd(dAtA, i, uint64(len(m.Title)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Index) > 0 {
		i -= len(m.Index)
		copy(dAtA[i:], m.Index)
		i = encodeVarintAd(dAtA, i, uint64(len(m.Index)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintAd(dAtA []byte, offset int, v uint64) int {
	offset -= sovAd(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Ad) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Index)
	if l > 0 {
		n += 1 + l + sovAd(uint64(l))
	}
	l = len(m.Title)
	if l > 0 {
		n += 1 + l + sovAd(uint64(l))
	}
	if m.Pot != 0 {
		n += 1 + sovAd(uint64(m.Pot))
	}
	l = len(m.Url)
	if l > 0 {
		n += 1 + l + sovAd(uint64(l))
	}
	l = len(m.Msg)
	if l > 0 {
		n += 1 + l + sovAd(uint64(l))
	}
	l = len(m.Tags)
	if l > 0 {
		n += 1 + l + sovAd(uint64(l))
	}
	l = len(m.Prefs)
	if l > 0 {
		n += 1 + l + sovAd(uint64(l))
	}
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovAd(uint64(l))
	}
	return n
}

func sovAd(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozAd(x uint64) (n int) {
	return sovAd(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Ad) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAd
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Ad: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Ad: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAd
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAd
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAd
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Index = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Title", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAd
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAd
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAd
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Title = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pot", wireType)
			}
			m.Pot = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAd
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Pot |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Url", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAd
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAd
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAd
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Url = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Msg", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAd
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAd
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAd
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Msg = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tags", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAd
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAd
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAd
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Tags = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Prefs", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAd
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAd
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAd
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Prefs = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAd
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAd
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAd
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAd(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAd
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipAd(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowAd
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAd
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAd
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthAd
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupAd
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthAd
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthAd        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowAd          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupAd = fmt.Errorf("proto: unexpected end of group")
)
