// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: zestchain/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b96b9adafafa773, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b96b9adafafa773, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryGetPromoCountRequest struct {
}

func (m *QueryGetPromoCountRequest) Reset()         { *m = QueryGetPromoCountRequest{} }
func (m *QueryGetPromoCountRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetPromoCountRequest) ProtoMessage()    {}
func (*QueryGetPromoCountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b96b9adafafa773, []int{2}
}
func (m *QueryGetPromoCountRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetPromoCountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetPromoCountRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetPromoCountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetPromoCountRequest.Merge(m, src)
}
func (m *QueryGetPromoCountRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetPromoCountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetPromoCountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetPromoCountRequest proto.InternalMessageInfo

type QueryGetPromoCountResponse struct {
	PromoCount PromoCount `protobuf:"bytes,1,opt,name=PromoCount,proto3" json:"PromoCount"`
}

func (m *QueryGetPromoCountResponse) Reset()         { *m = QueryGetPromoCountResponse{} }
func (m *QueryGetPromoCountResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetPromoCountResponse) ProtoMessage()    {}
func (*QueryGetPromoCountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b96b9adafafa773, []int{3}
}
func (m *QueryGetPromoCountResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetPromoCountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetPromoCountResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetPromoCountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetPromoCountResponse.Merge(m, src)
}
func (m *QueryGetPromoCountResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetPromoCountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetPromoCountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetPromoCountResponse proto.InternalMessageInfo

func (m *QueryGetPromoCountResponse) GetPromoCount() PromoCount {
	if m != nil {
		return m.PromoCount
	}
	return PromoCount{}
}

type QueryGetPromoRequest struct {
	Index string `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
}

func (m *QueryGetPromoRequest) Reset()         { *m = QueryGetPromoRequest{} }
func (m *QueryGetPromoRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetPromoRequest) ProtoMessage()    {}
func (*QueryGetPromoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b96b9adafafa773, []int{4}
}
func (m *QueryGetPromoRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetPromoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetPromoRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetPromoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetPromoRequest.Merge(m, src)
}
func (m *QueryGetPromoRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetPromoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetPromoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetPromoRequest proto.InternalMessageInfo

func (m *QueryGetPromoRequest) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

type QueryGetPromoResponse struct {
	Promo Promo `protobuf:"bytes,1,opt,name=promo,proto3" json:"promo"`
}

func (m *QueryGetPromoResponse) Reset()         { *m = QueryGetPromoResponse{} }
func (m *QueryGetPromoResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetPromoResponse) ProtoMessage()    {}
func (*QueryGetPromoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b96b9adafafa773, []int{5}
}
func (m *QueryGetPromoResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetPromoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetPromoResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetPromoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetPromoResponse.Merge(m, src)
}
func (m *QueryGetPromoResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetPromoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetPromoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetPromoResponse proto.InternalMessageInfo

func (m *QueryGetPromoResponse) GetPromo() Promo {
	if m != nil {
		return m.Promo
	}
	return Promo{}
}

type QueryAllPromoRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllPromoRequest) Reset()         { *m = QueryAllPromoRequest{} }
func (m *QueryAllPromoRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllPromoRequest) ProtoMessage()    {}
func (*QueryAllPromoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b96b9adafafa773, []int{6}
}
func (m *QueryAllPromoRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllPromoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllPromoRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllPromoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllPromoRequest.Merge(m, src)
}
func (m *QueryAllPromoRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllPromoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllPromoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllPromoRequest proto.InternalMessageInfo

func (m *QueryAllPromoRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllPromoResponse struct {
	Promo      []Promo             `protobuf:"bytes,1,rep,name=promo,proto3" json:"promo"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllPromoResponse) Reset()         { *m = QueryAllPromoResponse{} }
func (m *QueryAllPromoResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllPromoResponse) ProtoMessage()    {}
func (*QueryAllPromoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b96b9adafafa773, []int{7}
}
func (m *QueryAllPromoResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllPromoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllPromoResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllPromoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllPromoResponse.Merge(m, src)
}
func (m *QueryAllPromoResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllPromoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllPromoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllPromoResponse proto.InternalMessageInfo

func (m *QueryAllPromoResponse) GetPromo() []Promo {
	if m != nil {
		return m.Promo
	}
	return nil
}

func (m *QueryAllPromoResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "cytruslabs.zestchain.zestchain.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "cytruslabs.zestchain.zestchain.QueryParamsResponse")
	proto.RegisterType((*QueryGetPromoCountRequest)(nil), "cytruslabs.zestchain.zestchain.QueryGetPromoCountRequest")
	proto.RegisterType((*QueryGetPromoCountResponse)(nil), "cytruslabs.zestchain.zestchain.QueryGetPromoCountResponse")
	proto.RegisterType((*QueryGetPromoRequest)(nil), "cytruslabs.zestchain.zestchain.QueryGetPromoRequest")
	proto.RegisterType((*QueryGetPromoResponse)(nil), "cytruslabs.zestchain.zestchain.QueryGetPromoResponse")
	proto.RegisterType((*QueryAllPromoRequest)(nil), "cytruslabs.zestchain.zestchain.QueryAllPromoRequest")
	proto.RegisterType((*QueryAllPromoResponse)(nil), "cytruslabs.zestchain.zestchain.QueryAllPromoResponse")
}

func init() { proto.RegisterFile("zestchain/query.proto", fileDescriptor_3b96b9adafafa773) }

var fileDescriptor_3b96b9adafafa773 = []byte{
	// 559 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x94, 0x4f, 0x6f, 0xd3, 0x30,
	0x18, 0xc6, 0xeb, 0x41, 0x2b, 0x30, 0x37, 0xd3, 0x22, 0xc8, 0x50, 0x40, 0x91, 0xf6, 0x47, 0x83,
	0xc6, 0x6a, 0xcb, 0x0e, 0x70, 0xeb, 0x40, 0xec, 0xc0, 0xa5, 0xf4, 0x38, 0x24, 0x90, 0x13, 0xac,
	0x2c, 0x52, 0x1a, 0x67, 0xb1, 0x83, 0x56, 0x10, 0x17, 0x3e, 0x01, 0x12, 0x9f, 0x00, 0x21, 0x71,
	0xe1, 0x0b, 0x70, 0xe1, 0xbe, 0xe3, 0x24, 0x2e, 0x9c, 0x10, 0x6a, 0xf9, 0x20, 0x28, 0xb6, 0x3b,
	0xa7, 0x59, 0x45, 0xd3, 0xdd, 0x1c, 0xbf, 0xef, 0xf3, 0x3e, 0x3f, 0x59, 0xcf, 0x1b, 0xd8, 0x7a,
	0x4b, 0xb9, 0xf0, 0x0f, 0x49, 0x18, 0xe3, 0xa3, 0x8c, 0xa6, 0x63, 0x37, 0x49, 0x99, 0x60, 0xc8,
	0xf6, 0xc7, 0x22, 0xcd, 0x78, 0x44, 0x3c, 0xee, 0x9e, 0x75, 0x98, 0x93, 0xd5, 0x0c, 0x58, 0xc0,
	0x64, 0x2b, 0xce, 0x4f, 0x4a, 0x65, 0xdd, 0x0e, 0x18, 0x0b, 0x22, 0x8a, 0x49, 0x12, 0x62, 0x12,
	0xc7, 0x4c, 0x10, 0x11, 0xb2, 0x98, 0xeb, 0xea, 0x8e, 0xcf, 0xf8, 0x88, 0x71, 0xec, 0x11, 0x4e,
	0x95, 0x19, 0x7e, 0xd3, 0xf1, 0xa8, 0x20, 0x1d, 0x9c, 0x90, 0x20, 0x8c, 0x65, 0xb3, 0xee, 0xbd,
	0x61, 0xb0, 0x12, 0x92, 0x92, 0xd1, 0x6c, 0xc6, 0x7a, 0xe1, 0x3e, 0x65, 0x23, 0xf6, 0xca, 0x67,
	0x59, 0x2c, 0x74, 0xb1, 0x55, 0x2a, 0xaa, 0x6b, 0xa7, 0x09, 0xd1, 0xf3, 0xdc, 0x6d, 0x20, 0x07,
	0x0d, 0xe9, 0x51, 0x46, 0xb9, 0x70, 0x5e, 0xc0, 0xeb, 0x73, 0xb7, 0x3c, 0x61, 0x31, 0xa7, 0xe8,
	0x09, 0x6c, 0x28, 0xc3, 0x9b, 0xe0, 0x2e, 0xd8, 0xbe, 0xd6, 0xdd, 0x74, 0xff, 0xff, 0x12, 0xae,
	0xd2, 0xef, 0x5d, 0x3e, 0xf9, 0x7d, 0xa7, 0x36, 0xd4, 0x5a, 0x67, 0x1d, 0xde, 0x92, 0xc3, 0xf7,
	0xa9, 0x18, 0xe4, 0x24, 0x8f, 0x73, 0xca, 0x99, 0x73, 0x0c, 0xad, 0x45, 0x45, 0x0d, 0x30, 0x80,
	0xd0, 0xdc, 0x6a, 0x88, 0x9d, 0xa5, 0x10, 0x67, 0x0a, 0x0d, 0x52, 0x98, 0xe1, 0xdc, 0x87, 0xcd,
	0x39, 0x3f, 0xcd, 0x81, 0x9a, 0xb0, 0x1e, 0xc6, 0xaf, 0xe9, 0xb1, 0x34, 0xb9, 0x3a, 0x54, 0x1f,
	0xce, 0x01, 0x6c, 0x95, 0xba, 0x35, 0x58, 0x1f, 0xd6, 0xe5, 0xab, 0x6a, 0xa6, 0x8d, 0x4a, 0x4c,
	0x1a, 0x47, 0x29, 0x9d, 0x97, 0x9a, 0xa4, 0x1f, 0x45, 0x73, 0x24, 0x4f, 0x21, 0x34, 0x09, 0x30,
	0x0f, 0x2f, 0xe3, 0xe2, 0xe6, 0x71, 0x71, 0x55, 0x36, 0x75, 0x5c, 0xdc, 0x01, 0x09, 0xa8, 0xd6,
	0x0e, 0x0b, 0x4a, 0xe7, 0x0b, 0xd0, 0xf0, 0xc6, 0xe0, 0x3c, 0xfc, 0xa5, 0x8b, 0xc1, 0xa3, 0xfd,
	0x39, 0xc8, 0x35, 0x09, 0xb9, 0xb5, 0x14, 0x52, 0xf9, 0x17, 0x29, 0xbb, 0x3f, 0xea, 0xb0, 0x2e,
	0x29, 0xd1, 0x67, 0x00, 0x1b, 0x2a, 0x3f, 0xa8, 0xbb, 0x8c, 0xe8, 0x7c, 0x84, 0xad, 0xde, 0x4a,
	0x1a, 0x45, 0xe2, 0xb8, 0x1f, 0x7e, 0xfe, 0xfd, 0xb4, 0xb6, 0x8d, 0x36, 0xb1, 0x11, 0x63, 0xb3,
	0x38, 0xe5, 0xbd, 0x43, 0xdf, 0x41, 0x31, 0x90, 0xe8, 0x61, 0x25, 0xcf, 0x45, 0xb9, 0xb7, 0x1e,
	0x5d, 0x44, 0xaa, 0xa9, 0x7b, 0x92, 0xba, 0x8d, 0xee, 0x2d, 0xa5, 0x36, 0x7f, 0x05, 0xf4, 0x0d,
	0xc0, 0xba, 0x9c, 0x85, 0x1e, 0xac, 0x64, 0x3d, 0x03, 0xde, 0x5d, 0x51, 0xa5, 0x59, 0x77, 0x25,
	0x2b, 0x46, 0xed, 0x4a, 0xac, 0xf8, 0x9d, 0xdc, 0xbb, 0xf7, 0xe8, 0x2b, 0x80, 0x57, 0xe4, 0xa0,
	0x7e, 0x14, 0x55, 0x04, 0x2e, 0xed, 0x51, 0x45, 0xe0, 0xf2, 0x72, 0x38, 0x6d, 0x09, 0xbc, 0x85,
	0x36, 0x2a, 0x01, 0xef, 0x3d, 0x3b, 0x99, 0xd8, 0xe0, 0x74, 0x62, 0x83, 0x3f, 0x13, 0x1b, 0x7c,
	0x9c, 0xda, 0xb5, 0xd3, 0xa9, 0x5d, 0xfb, 0x35, 0xb5, 0x6b, 0x07, 0x9d, 0x20, 0x14, 0x87, 0x99,
	0xe7, 0xfa, 0x6c, 0xb4, 0x78, 0xd4, 0x71, 0xe1, 0x2c, 0xc6, 0x09, 0xe5, 0x5e, 0x43, 0xfe, 0xa3,
	0x7b, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0x64, 0xcb, 0x1e, 0x6a, 0x88, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Queries a PromoCount by index.
	PromoCount(ctx context.Context, in *QueryGetPromoCountRequest, opts ...grpc.CallOption) (*QueryGetPromoCountResponse, error)
	// Queries a Promo by index.
	Promo(ctx context.Context, in *QueryGetPromoRequest, opts ...grpc.CallOption) (*QueryGetPromoResponse, error)
	// Queries a list of Promo items.
	PromoAll(ctx context.Context, in *QueryAllPromoRequest, opts ...grpc.CallOption) (*QueryAllPromoResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/cytruslabs.zestchain.zestchain.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) PromoCount(ctx context.Context, in *QueryGetPromoCountRequest, opts ...grpc.CallOption) (*QueryGetPromoCountResponse, error) {
	out := new(QueryGetPromoCountResponse)
	err := c.cc.Invoke(ctx, "/cytruslabs.zestchain.zestchain.Query/PromoCount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Promo(ctx context.Context, in *QueryGetPromoRequest, opts ...grpc.CallOption) (*QueryGetPromoResponse, error) {
	out := new(QueryGetPromoResponse)
	err := c.cc.Invoke(ctx, "/cytruslabs.zestchain.zestchain.Query/Promo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) PromoAll(ctx context.Context, in *QueryAllPromoRequest, opts ...grpc.CallOption) (*QueryAllPromoResponse, error) {
	out := new(QueryAllPromoResponse)
	err := c.cc.Invoke(ctx, "/cytruslabs.zestchain.zestchain.Query/PromoAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Queries a PromoCount by index.
	PromoCount(context.Context, *QueryGetPromoCountRequest) (*QueryGetPromoCountResponse, error)
	// Queries a Promo by index.
	Promo(context.Context, *QueryGetPromoRequest) (*QueryGetPromoResponse, error)
	// Queries a list of Promo items.
	PromoAll(context.Context, *QueryAllPromoRequest) (*QueryAllPromoResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) PromoCount(ctx context.Context, req *QueryGetPromoCountRequest) (*QueryGetPromoCountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PromoCount not implemented")
}
func (*UnimplementedQueryServer) Promo(ctx context.Context, req *QueryGetPromoRequest) (*QueryGetPromoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Promo not implemented")
}
func (*UnimplementedQueryServer) PromoAll(ctx context.Context, req *QueryAllPromoRequest) (*QueryAllPromoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PromoAll not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cytruslabs.zestchain.zestchain.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_PromoCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetPromoCountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).PromoCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cytruslabs.zestchain.zestchain.Query/PromoCount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).PromoCount(ctx, req.(*QueryGetPromoCountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Promo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetPromoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Promo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cytruslabs.zestchain.zestchain.Query/Promo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Promo(ctx, req.(*QueryGetPromoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_PromoAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllPromoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).PromoAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cytruslabs.zestchain.zestchain.Query/PromoAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).PromoAll(ctx, req.(*QueryAllPromoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cytruslabs.zestchain.zestchain.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "PromoCount",
			Handler:    _Query_PromoCount_Handler,
		},
		{
			MethodName: "Promo",
			Handler:    _Query_Promo_Handler,
		},
		{
			MethodName: "PromoAll",
			Handler:    _Query_PromoAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "zestchain/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryGetPromoCountRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetPromoCountRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetPromoCountRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryGetPromoCountResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetPromoCountResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetPromoCountResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.PromoCount.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryGetPromoRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetPromoRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetPromoRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Index) > 0 {
		i -= len(m.Index)
		copy(dAtA[i:], m.Index)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Index)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetPromoResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetPromoResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetPromoResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Promo.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllPromoRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllPromoRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllPromoRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllPromoResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllPromoResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllPromoResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Promo) > 0 {
		for iNdEx := len(m.Promo) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Promo[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGetPromoCountRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryGetPromoCountResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.PromoCount.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGetPromoRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Index)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetPromoResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Promo.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllPromoRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllPromoResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Promo) > 0 {
		for _, e := range m.Promo {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetPromoCountRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetPromoCountRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetPromoCountRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetPromoCountResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetPromoCountResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetPromoCountResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PromoCount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.PromoCount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetPromoRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetPromoRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetPromoRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Index = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetPromoResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetPromoResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetPromoResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Promo", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Promo.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllPromoRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllPromoRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllPromoRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllPromoResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllPromoResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllPromoResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Promo", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Promo = append(m.Promo, Promo{})
			if err := m.Promo[len(m.Promo)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
